#!/bin/sh
printf "GCM_INTERACTIVE=%s\n" "${GCM_INTERACTIVE:-}" > "$YANTRIX_TEST_SSH_ASKPASS_LOG"
printf "GIT_ASKPASS=%s\n" "${GIT_ASKPASS:-}" >> "$YANTRIX_TEST_SSH_ASKPASS_LOG"
printf "GIT_TERMINAL_PROMPT=%s\n" "${GIT_TERMINAL_PROMPT:-}" >> "$YANTRIX_TEST_SSH_ASKPASS_LOG"
printf "SSH_ASKPASS=%s\n" "${SSH_ASKPASS:-}" >> "$YANTRIX_TEST_SSH_ASKPASS_LOG"
printf "SSH_ASKPASS_REQUIRE=%s\n" "${SSH_ASKPASS_REQUIRE:-}" >> "$YANTRIX_TEST_SSH_ASKPASS_LOG"
exit 1
